services:
  - type: web
    name: docusortai-backend
    rootDir: backend
    runtime: docker
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: HF_API_KEY
        sync: false
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: documents

  - type: web
    name: docusortai-frontend
    rootDir: frontend
    runtime: static
    buildCommand: yarn install && yarn build
    staticPublishPath: build
    autoDeploy: true
