services:
  - type: web
    name: docusort-backend
    runtime: python
    rootDir: backend
    buildCommand: "apt-get update && apt-get install -y poppler-utils ffmpeg libsm6 libxext6 libgl1 && pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"