services:
  - type: web
    name: docusort-backend
    runtime: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
  - type: web
    name: docusort-frontend
    runtime: static
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
